version: '3'
services:
  catalog:
    container_name: video-code-catalog
    build: ./catalog
    volumes:
      - ./catalog:/var/www/
    networks:
      - video-code
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"

  nginx:
    container_name: video-code-nginx
    image: nginx:1.21
    volumes:
      - ./catalog:/var/www/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - video-code
    ports:
      - "8000:80"

  bd:
    container_name: video-code-mysql
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d/
    networks:
      - video-code
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"


networks:
  video-code:
    driver: bridge
volumes:
  mysql: