on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: catalog
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: catalog_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: |
        composer install
    
    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Run Testsuite
      env:
        DB_PASSWORD: password
      run: vendor/bin/phpunit tests/
